networks:
  odooNetwork:
    driver: bridge

volumes:
  db-data:
  odoo-data:
  traefik_acme:

services:
  postgresql:
    container_name: postgresql
    image: postgres:${DB_VERSION}
    # restart: unless-stopped
    networks: [odooNetwork]
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PWD}
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis:7
    # restart: unless-stopped
    networks: [odooNetwork]
    command: ["redis-server","--save","","--appendonly","no"]

  odoo:
    image: odoo:${ODOO_VERSION}
    # restart: unless-stopped
    depends_on:
      - postgresql
      - redis
    networks: [odooNetwork]
    environment:
    - HOST=postgresql
    - PORT=5432
    - USER=${DB_USER}
    - PASSWORD=${DB_PWD}

    user: "100:101"
    volumes:
      - ./odoo-data:/var/lib/odoo
      # - odoo-data:/var/lib/odoo
      - ./odoo.conf:/etc/odoo/odoo.conf:ro
      # - ./enterprise:/mnt/enterprise:ro
      # - ./extra-addons:/mnt/extra-addons:ro

  traefik:
    image: traefik:v3.5
    environment:
      - INFOMANIAK_ACCESS_TOKEN=${INFOMANIAK_ACCESS_TOKEN}
    command:
      - "--entrypoints.lan.address=:443"            # 443 interne Traefik (LAN)
      - "--entrypoints.wan.address=:8443"           # 8443 interne Traefik (WAN)
      - "--providers.file.directory=/etc/traefik/dynamic"
      - "--providers.file.watch=true"

      # --- ACME / Let's Encrypt via DNS-01 (Infomaniak)
      - "--certificatesresolvers.le-dns.acme.email=info@udrytech.ch"
      - "--certificatesresolvers.le-dns.acme.storage=/acme/acme.json"
      - "--certificatesresolvers.le-dns.acme.dnschallenge.provider=infomaniak"
      - "--certificatesresolvers.le-dns.acme.dnschallenge.delaybeforecheck=0"
      - "--certificatesresolvers.myresolver.acme.dnschallenge=true"
    networks:
      - odooNetwork
    ports:
      - "443:443"          # accès LAN direct
      - "8443:8443"        # routeur 443 -> hôte 8443 -> Traefik:8443
    volumes:
      - ./traefik/dynamic:/etc/traefik/dynamic:ro
      - ./traefik/acme:/acme
    restart: unless-stopped
