networks:
  odooNetwork:
    driver: bridge

volumes:
  db-data:
  odoo-data:
  traefik_acme:

services:
  postgresql:
    container_name: postgresql
    image: postgres:${DB_VERSION}
    # restart: unless-stopped
    networks: [odooNetwork]
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PWD}
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis:7
    # restart: unless-stopped
    networks: [odooNetwork]
    command: ["redis-server","--save","","--appendonly","no"]

  odoo:
    image: odoo:${ODOO_VERSION}
    # restart: unless-stopped
    depends_on:
      - postgresql
      - redis
    networks: [odooNetwork]
    environment:
    - HOST=postgresql
    - PORT=5432
    - USER=${DB_USER}
    - PASSWORD=${DB_PWD}

    user: "100:101"
    volumes:
      - ./odoo-data:/var/lib/odoo
      # - odoo-data:/var/lib/odoo
      - ./odoo.conf:/etc/odoo/odoo.conf:ro
      # - ./enterprise:/mnt/enterprise:ro
      # - ./extra-addons:/mnt/extra-addons:ro

  traefik:
      image: traefik:v3.1
      container_name: traefik
      command:
        # providers
        - --providers.file.directory=/etc/traefik/dynamic
        - --providers.file.watch=true
        # Redirection http to https
        - --entrypoints.http.address=:80
        - --entrypoints.http.http.redirections.entrypoint.to=lan
        - --entrypoints.http.http.redirections.entrypoint.scheme=https
        # entrypoints: LAN=443  /  WAN=8443
        - --entrypoints.lan.address=:443
        - --entrypoints.wan.address=:8443
        - --log.level=WARN
        - --accesslog=true
        # ACME (DNS-01) -> décommente et adapte si tu veux l’externe maintenant
        # - --certificatesresolvers.le-dns.acme.email=admin@udryconstruction.ch
        # - --certificatesresolvers.le-dns.acme.storage=/acme/acme.json
        # - --certificatesresolvers.le-dns.acme.dnschallenge.provider=cloudflare
        # - --certificatesresolvers.le-dns.acme.dnschallenge.delaybeforecheck=5
        # (optionnel) staging pour tests:
        # - --certificatesresolvers.le-dns.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory
      ports:
        - "80:80"
        - "443:443"     # LAN direct
        - "8443:8443"   # WAN via box 443->8443
        # si tu choisis ACME HTTP-01 à la place de DNS-01, ajoute:
        # - "80:80"
      # environment:
        # pour DNS-01 (ex Cloudflare) – si tu l’utilises
        # CF_DNS_API_TOKEN: "${CF_DNS_API_TOKEN}"
      volumes:
        - ./traefik/dynamic:/etc/traefik/dynamic:ro
        - traefik_acme:/acme
      networks:
        - odooNetwork
      restart: unless-stopped
